server:
  port: 8083

spring:
  application:
    name: chat-service
  
  # 로컬 개발용 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/dorandoran_local
    username: doran
    password: doran
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 개발 시에는 update 사용
      default_schema: chat
    show-sql: true  # 개발 시 SQL 로그 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# 로깅 설정
logging:
  level:
    com.dorandoran.chat: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always
