--
-- PostgreSQL database dump
--

\restrict k1AwuoK1JB5INgXavvsiHAJKQfNWiM1z5rNrMeziwVwOumkgAZpUxgiJUXe86kg

-- Dumped from database version 17.6
-- Dumped by pg_dump version 17.6

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: auth_schema; Type: SCHEMA; Schema: -; Owner: doran
--

CREATE SCHEMA auth_schema;


ALTER SCHEMA auth_schema OWNER TO doran;

--
-- Name: batch_schema; Type: SCHEMA; Schema: -; Owner: doran
--

CREATE SCHEMA batch_schema;


ALTER SCHEMA batch_schema OWNER TO doran;

--
-- Name: billing; Type: SCHEMA; Schema: -; Owner: doran
--

CREATE SCHEMA billing;


ALTER SCHEMA billing OWNER TO doran;

--
-- Name: chat_schema; Type: SCHEMA; Schema: -; Owner: doran
--

CREATE SCHEMA chat_schema;


ALTER SCHEMA chat_schema OWNER TO doran;

--
-- Name: store_schema; Type: SCHEMA; Schema: -; Owner: doran
--

CREATE SCHEMA store_schema;


ALTER SCHEMA store_schema OWNER TO doran;

--
-- Name: user_schema; Type: SCHEMA; Schema: -; Owner: doran
--

CREATE SCHEMA user_schema;


ALTER SCHEMA user_schema OWNER TO doran;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_events; Type: TABLE; Schema: auth_schema; Owner: doran
--

CREATE TABLE auth_schema.auth_events (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    event_type character varying(50) NOT NULL,
    metadata text,
    user_id uuid
);


ALTER TABLE auth_schema.auth_events OWNER TO doran;

--
-- Name: auth_events_id_seq; Type: SEQUENCE; Schema: auth_schema; Owner: doran
--

ALTER TABLE auth_schema.auth_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth_schema.auth_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_verifications; Type: TABLE; Schema: auth_schema; Owner: doran
--

CREATE TABLE auth_schema.email_verifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(128) NOT NULL,
    verified boolean NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE auth_schema.email_verifications OWNER TO doran;

--
-- Name: email_verifications_id_seq; Type: SEQUENCE; Schema: auth_schema; Owner: doran
--

ALTER TABLE auth_schema.email_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth_schema.email_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: login_attempts; Type: TABLE; Schema: auth_schema; Owner: doran
--

CREATE TABLE auth_schema.login_attempts (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    email character varying(320),
    ip_address character varying(255),
    succeeded boolean NOT NULL,
    user_agent character varying(500),
    user_id uuid
);


ALTER TABLE auth_schema.login_attempts OWNER TO doran;

--
-- Name: login_attempts_id_seq; Type: SEQUENCE; Schema: auth_schema; Owner: doran
--

ALTER TABLE auth_schema.login_attempts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth_schema.login_attempts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: auth_schema; Owner: doran
--

CREATE TABLE auth_schema.password_reset_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token_hash character varying(128) NOT NULL,
    used boolean NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE auth_schema.password_reset_tokens OWNER TO doran;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: auth_schema; Owner: doran
--

ALTER TABLE auth_schema.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth_schema.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: auth_schema; Owner: doran
--

CREATE TABLE auth_schema.refresh_tokens (
    id bigint NOT NULL,
    device_id character varying(200),
    expires_at timestamp(6) without time zone NOT NULL,
    ip_address character varying(255),
    issued_at timestamp(6) without time zone NOT NULL,
    revoked boolean NOT NULL,
    rotated_from_id bigint,
    token text NOT NULL,
    user_agent character varying(500),
    user_id uuid NOT NULL
);


ALTER TABLE auth_schema.refresh_tokens OWNER TO doran;

--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: auth_schema; Owner: doran
--

ALTER TABLE auth_schema.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth_schema.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist; Type: TABLE; Schema: auth_schema; Owner: doran
--

CREATE TABLE auth_schema.token_blacklist (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    reason character varying(200),
    token_hash character varying(128) NOT NULL,
    token_type character varying(20) NOT NULL
);


ALTER TABLE auth_schema.token_blacklist OWNER TO doran;

--
-- Name: token_blacklist_id_seq; Type: SEQUENCE; Schema: auth_schema; Owner: doran
--

ALTER TABLE auth_schema.token_blacklist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME auth_schema.token_blacklist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_usage_events; Type: TABLE; Schema: billing; Owner: doran
--

CREATE TABLE billing.ai_usage_events (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    event_time timestamp without time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    chatroom_id uuid NOT NULL,
    provider text NOT NULL,
    model text NOT NULL,
    request_id text,
    input_tokens integer DEFAULT 0 NOT NULL,
    output_tokens integer DEFAULT 0 NOT NULL,
    cost_in numeric(18,6) DEFAULT 0 NOT NULL,
    cost_out numeric(18,6) DEFAULT 0 NOT NULL,
    meta jsonb
);


ALTER TABLE billing.ai_usage_events OWNER TO doran;

--
-- Name: monthly_user_costs; Type: TABLE; Schema: billing; Owner: doran
--

CREATE TABLE billing.monthly_user_costs (
    billing_month date NOT NULL,
    user_id uuid NOT NULL,
    input_tokens bigint DEFAULT 0 NOT NULL,
    output_tokens bigint DEFAULT 0 NOT NULL,
    cost_in numeric(18,6) DEFAULT 0 NOT NULL,
    cost_out numeric(18,6) DEFAULT 0 NOT NULL,
    total_cost numeric(18,6) DEFAULT 0 NOT NULL,
    last_aggregated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE billing.monthly_user_costs OWNER TO doran;

--
-- Name: chatbots; Type: TABLE; Schema: chat_schema; Owner: doran
--

CREATE TABLE chat_schema.chatbots (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    display_name character varying(100) NOT NULL,
    description text,
    bot_type character varying(50) NOT NULL,
    model_name character varying(100),
    personality jsonb,
    system_prompt text,
    capabilities jsonb,
    settings jsonb,
    intimacy_level integer DEFAULT 1,
    avatar_url character varying(500),
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    created_by uuid,
    intimacy_system_prompt text,
    intimacy_user_prompt text,
    vocabulary_system_prompt text,
    vocabulary_user_prompt text,
    translation_system_prompt text,
    translation_user_prompt text,
    CONSTRAINT chatbots_intimacy_level_check CHECK (((intimacy_level >= 1) AND (intimacy_level <= 3))),
    CONSTRAINT chk_chatbots_type CHECK (((bot_type)::text = ANY (ARRAY[('gpt'::character varying)::text, ('claude'::character varying)::text, ('custom'::character varying)::text])))
);


ALTER TABLE chat_schema.chatbots OWNER TO doran;

--
-- Name: TABLE chatbots; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON TABLE chat_schema.chatbots IS 'AI 챗봇';


--
-- Name: COLUMN chatbots.id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.id IS '챗봇 아이디';


--
-- Name: COLUMN chatbots.name; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.name IS '챗봇 이름';


--
-- Name: COLUMN chatbots.display_name; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.display_name IS '표시 이름';


--
-- Name: COLUMN chatbots.description; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.description IS '챗봇 설명';


--
-- Name: COLUMN chatbots.bot_type; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.bot_type IS '챗봇 타입 (gpt, claude, custom)';


--
-- Name: COLUMN chatbots.model_name; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.model_name IS 'AI 모델명';


--
-- Name: COLUMN chatbots.personality; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.personality IS '챗봇 성격 설정 (JSONB)';


--
-- Name: COLUMN chatbots.system_prompt; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.system_prompt IS '시스템 프롬프트';


--
-- Name: COLUMN chatbots.capabilities; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.capabilities IS '챗봇 기능 설정 (JSONB)';


--
-- Name: COLUMN chatbots.settings; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.settings IS '챗봇 설정 (JSONB)';


--
-- Name: COLUMN chatbots.intimacy_level; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.intimacy_level IS '친밀도 레벨 (1=격식체, 2=부드러운 존댓말, 3=반말)';


--
-- Name: COLUMN chatbots.avatar_url; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.avatar_url IS '아바타 URL';


--
-- Name: COLUMN chatbots.is_active; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.is_active IS '활성 상태';


--
-- Name: COLUMN chatbots.created_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.created_at IS '생성 시간';


--
-- Name: COLUMN chatbots.updated_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.updated_at IS '수정 시간';


--
-- Name: COLUMN chatbots.created_by; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatbots.created_by IS '생성자';


--
-- Name: chatrooms; Type: TABLE; Schema: chat_schema; Owner: doran
--

CREATE TABLE chat_schema.chatrooms (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    name character varying(100) NOT NULL,
    description text,
    chatbot_id uuid NOT NULL,
    user_id uuid NOT NULL,
    settings jsonb DEFAULT '{}'::jsonb,
    context_data jsonb,
    last_message_at timestamp without time zone,
    last_message_id uuid,
    is_archived boolean DEFAULT false,
    is_deleted boolean DEFAULT false,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now()
);


ALTER TABLE chat_schema.chatrooms OWNER TO doran;

--
-- Name: TABLE chatrooms; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON TABLE chat_schema.chatrooms IS '채팅방';


--
-- Name: COLUMN chatrooms.id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.id IS '채팅방 아이디';


--
-- Name: COLUMN chatrooms.name; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.name IS '채팅방 이름';


--
-- Name: COLUMN chatrooms.description; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.description IS '채팅방 설명';


--
-- Name: COLUMN chatrooms.chatbot_id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.chatbot_id IS '챗봇 아이디';


--
-- Name: COLUMN chatrooms.user_id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.user_id IS '사용자 아이디';


--
-- Name: COLUMN chatrooms.settings; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.settings IS '채팅방 설정 (JSONB)';


--
-- Name: COLUMN chatrooms.context_data; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.context_data IS '대화 컨텍스트 데이터 (JSONB)';


--
-- Name: COLUMN chatrooms.last_message_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.last_message_at IS '마지막 메시지 시간';


--
-- Name: COLUMN chatrooms.last_message_id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.last_message_id IS '마지막 메시지 아이디';


--
-- Name: COLUMN chatrooms.is_archived; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.is_archived IS '아카이브 여부';


--
-- Name: COLUMN chatrooms.is_deleted; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.is_deleted IS '삭제 여부';


--
-- Name: COLUMN chatrooms.created_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.created_at IS '생성 시간';


--
-- Name: COLUMN chatrooms.updated_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.chatrooms.updated_at IS '수정 시간';


--
-- Name: flyway_schema_history; Type: TABLE; Schema: chat_schema; Owner: doran
--

CREATE TABLE chat_schema.flyway_schema_history (
    installed_rank integer NOT NULL,
    version character varying(50),
    description character varying(200) NOT NULL,
    type character varying(20) NOT NULL,
    script character varying(1000) NOT NULL,
    checksum integer,
    installed_by character varying(100) NOT NULL,
    installed_on timestamp without time zone DEFAULT now() NOT NULL,
    execution_time integer NOT NULL,
    success boolean NOT NULL
);


ALTER TABLE chat_schema.flyway_schema_history OWNER TO doran;

--
-- Name: intimacy_progress; Type: TABLE; Schema: chat_schema; Owner: doran
--

CREATE TABLE chat_schema.intimacy_progress (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    chatroom_id uuid NOT NULL,
    user_id uuid NOT NULL,
    intimacy_level integer DEFAULT 1 NOT NULL,
    total_corrections integer DEFAULT 0,
    last_feedback text,
    last_updated timestamp without time zone DEFAULT now(),
    progress_data jsonb,
    CONSTRAINT intimacy_progress_intimacy_level_check CHECK ((intimacy_level = ANY (ARRAY[1, 2, 3])))
);


ALTER TABLE chat_schema.intimacy_progress OWNER TO doran;

--
-- Name: TABLE intimacy_progress; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON TABLE chat_schema.intimacy_progress IS '채팅방별 친밀도 진척 추적';


--
-- Name: COLUMN intimacy_progress.intimacy_level; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.intimacy_progress.intimacy_level IS '현재 친밀도 레벨 (1=격식체, 2=부드러운 존댓말, 3=반말)';


--
-- Name: COLUMN intimacy_progress.total_corrections; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.intimacy_progress.total_corrections IS '누적 교정 횟수';


--
-- Name: COLUMN intimacy_progress.last_feedback; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.intimacy_progress.last_feedback IS '마지막 피드백 메시지';


--
-- Name: COLUMN intimacy_progress.progress_data; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.intimacy_progress.progress_data IS '세부 학습 통계 (JSONB)';


--
-- Name: messages; Type: TABLE; Schema: chat_schema; Owner: doran
--

CREATE TABLE chat_schema.messages (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    chatroom_id uuid NOT NULL,
    sender_type character varying(20) NOT NULL,
    sender_id uuid,
    content text NOT NULL,
    content_type character varying(20) DEFAULT 'text'::character varying,
    metadata jsonb,
    parent_message_id uuid,
    sequence_number bigint NOT NULL,
    token_count integer,
    processing_time_ms integer,
    is_edited boolean DEFAULT false,
    edited_at timestamp without time zone,
    is_deleted boolean DEFAULT false,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now(),
    updated_at timestamp without time zone DEFAULT now(),
    CONSTRAINT messages_content_type_check CHECK (((content_type)::text = ANY (ARRAY[('text'::character varying)::text, ('code'::character varying)::text, ('system'::character varying)::text, ('json'::character varying)::text]))),
    CONSTRAINT messages_sender_type_check CHECK (((sender_type)::text = ANY (ARRAY[('user'::character varying)::text, ('bot'::character varying)::text, ('system'::character varying)::text])))
);


ALTER TABLE chat_schema.messages OWNER TO doran;

--
-- Name: TABLE messages; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON TABLE chat_schema.messages IS '메시지';


--
-- Name: COLUMN messages.id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.id IS '메시지 아이디';


--
-- Name: COLUMN messages.chatroom_id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.chatroom_id IS '채팅방 아이디';


--
-- Name: COLUMN messages.sender_type; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.sender_type IS '발신자 타입 (user, bot, system)';


--
-- Name: COLUMN messages.sender_id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.sender_id IS '발신자 아이디';


--
-- Name: COLUMN messages.content; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.content IS '메시지 내용';


--
-- Name: COLUMN messages.content_type; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.content_type IS '콘텐츠 타입 (text, code, system)';


--
-- Name: COLUMN messages.metadata; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.metadata IS '메타데이터 (JSONB)';


--
-- Name: COLUMN messages.parent_message_id; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.parent_message_id IS '부모 메시지 아이디';


--
-- Name: COLUMN messages.sequence_number; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.sequence_number IS '대화 순서 번호';


--
-- Name: COLUMN messages.token_count; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.token_count IS '토큰 수';


--
-- Name: COLUMN messages.processing_time_ms; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.processing_time_ms IS '처리 시간 (밀리초)';


--
-- Name: COLUMN messages.is_edited; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.is_edited IS '수정 여부';


--
-- Name: COLUMN messages.edited_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.edited_at IS '수정 시간';


--
-- Name: COLUMN messages.is_deleted; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.is_deleted IS '삭제 여부';


--
-- Name: COLUMN messages.deleted_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.deleted_at IS '삭제 시간';


--
-- Name: COLUMN messages.created_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.created_at IS '생성 시간';


--
-- Name: COLUMN messages.updated_at; Type: COMMENT; Schema: chat_schema; Owner: doran
--

COMMENT ON COLUMN chat_schema.messages.updated_at IS '수정 시간';


--
-- Name: stores; Type: TABLE; Schema: store_schema; Owner: doran
--

CREATE TABLE store_schema.stores (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    user_id uuid NOT NULL,
    message_id uuid NOT NULL,
    chatroom_id uuid NOT NULL,
    content text NOT NULL,
    corrected_content text,
    ai_response jsonb NOT NULL,
    bot_type character varying(20),
    is_deleted boolean DEFAULT false NOT NULL,
    deleted_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE store_schema.stores OWNER TO doran;

--
-- Name: TABLE stores; Type: COMMENT; Schema: store_schema; Owner: doran
--

COMMENT ON TABLE store_schema.stores IS '보관함 - 사용자가 저장한 표현과 AI 응답';


--
-- Name: COLUMN stores.content; Type: COMMENT; Schema: store_schema; Owner: doran
--

COMMENT ON COLUMN store_schema.stores.content IS '표현 원본';


--
-- Name: COLUMN stores.corrected_content; Type: COMMENT; Schema: store_schema; Owner: doran
--

COMMENT ON COLUMN store_schema.stores.corrected_content IS '친밀도 Agent가 교정한 문장 (교정 없으면 NULL)';


--
-- Name: COLUMN stores.ai_response; Type: COMMENT; Schema: store_schema; Owner: doran
--

COMMENT ON COLUMN store_schema.stores.ai_response IS 'Multi-Agent AI 응답 (JSONB)';


--
-- Name: COLUMN stores.bot_type; Type: COMMENT; Schema: store_schema; Owner: doran
--

COMMENT ON COLUMN store_schema.stores.bot_type IS '챗봇 역할 (Honey, Coworker, Senior, Client)';


--
-- Name: app_user; Type: TABLE; Schema: user_schema; Owner: doran
--

CREATE TABLE user_schema.app_user (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    email character varying(320) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    name character varying(50) NOT NULL,
    password_hash character varying(100) NOT NULL,
    picture character varying(255),
    info character varying(100) DEFAULT ''::character varying NOT NULL,
    last_conn_time timestamp without time zone DEFAULT now() NOT NULL,
    status character varying(255) DEFAULT 'ACTIVE'::character varying NOT NULL,
    role character varying(20) DEFAULT 'ROLE_USER'::character varying NOT NULL,
    coach_check boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_app_user_role CHECK (((role)::text = ANY (ARRAY[('ROLE_USER'::character varying)::text, ('ROLE_ADMIN'::character varying)::text]))),
    CONSTRAINT chk_app_user_status CHECK (((status)::text = ANY (ARRAY[('ACTIVE'::character varying)::text, ('INACTIVE'::character varying)::text, ('SUSPENDED'::character varying)::text])))
);


ALTER TABLE user_schema.app_user OWNER TO doran;

--
-- Name: TABLE app_user; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON TABLE user_schema.app_user IS '사용자 정보';


--
-- Name: COLUMN app_user.id; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.id IS '사용자 아이디';


--
-- Name: COLUMN app_user.email; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.email IS '사용자 이메일';


--
-- Name: COLUMN app_user.first_name; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.first_name IS '이름';


--
-- Name: COLUMN app_user.last_name; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.last_name IS '성';


--
-- Name: COLUMN app_user.name; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.name IS '전체 이름';


--
-- Name: COLUMN app_user.password_hash; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.password_hash IS '비밀번호 해시';


--
-- Name: COLUMN app_user.picture; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.picture IS '프로필 사진';


--
-- Name: COLUMN app_user.info; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.info IS '사용자 정보';


--
-- Name: COLUMN app_user.last_conn_time; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.last_conn_time IS '마지막 연결 시간';


--
-- Name: COLUMN app_user.status; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.status IS '사용자 상태 (ACTIVE, INACTIVE, SUSPENDED)';


--
-- Name: COLUMN app_user.role; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.role IS '사용자 역할 (ROLE_USER, ROLE_ADMIN)';


--
-- Name: COLUMN app_user.coach_check; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.coach_check IS '코치 체크 여부';


--
-- Name: COLUMN app_user.created_at; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.created_at IS '생성 시간';


--
-- Name: COLUMN app_user.updated_at; Type: COMMENT; Schema: user_schema; Owner: doran
--

COMMENT ON COLUMN user_schema.app_user.updated_at IS '수정 시간';


--
-- Name: profiles; Type: TABLE; Schema: user_schema; Owner: doran
--

CREATE TABLE user_schema.profiles (
    id bigint NOT NULL,
    avatar_url character varying(500),
    bio text,
    created_at timestamp(6) without time zone NOT NULL,
    settings jsonb,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE user_schema.profiles OWNER TO doran;

--
-- Name: profiles_id_seq; Type: SEQUENCE; Schema: user_schema; Owner: doran
--

ALTER TABLE user_schema.profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_schema.profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settings; Type: TABLE; Schema: user_schema; Owner: doran
--

CREATE TABLE user_schema.settings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    setting_key character varying(100) NOT NULL,
    setting_value text,
    updated_at timestamp(6) without time zone NOT NULL,
    user_id uuid NOT NULL
);


ALTER TABLE user_schema.settings OWNER TO doran;

--
-- Name: settings_id_seq; Type: SEQUENCE; Schema: user_schema; Owner: doran
--

ALTER TABLE user_schema.settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME user_schema.settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_events auth_events_pkey; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.auth_events
    ADD CONSTRAINT auth_events_pkey PRIMARY KEY (id);


--
-- Name: email_verifications email_verifications_pkey; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.email_verifications
    ADD CONSTRAINT email_verifications_pkey PRIMARY KEY (id);


--
-- Name: login_attempts login_attempts_pkey; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.login_attempts
    ADD CONSTRAINT login_attempts_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist token_blacklist_pkey; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.token_blacklist
    ADD CONSTRAINT token_blacklist_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist uk85fjfavynxyo748kpsj9o6if1; Type: CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.token_blacklist
    ADD CONSTRAINT uk85fjfavynxyo748kpsj9o6if1 UNIQUE (token_hash);


--
-- Name: ai_usage_events ai_usage_events_pkey; Type: CONSTRAINT; Schema: billing; Owner: doran
--

ALTER TABLE ONLY billing.ai_usage_events
    ADD CONSTRAINT ai_usage_events_pkey PRIMARY KEY (id);


--
-- Name: ai_usage_events ai_usage_events_request_id_key; Type: CONSTRAINT; Schema: billing; Owner: doran
--

ALTER TABLE ONLY billing.ai_usage_events
    ADD CONSTRAINT ai_usage_events_request_id_key UNIQUE (request_id);


--
-- Name: monthly_user_costs monthly_user_costs_pk; Type: CONSTRAINT; Schema: billing; Owner: doran
--

ALTER TABLE ONLY billing.monthly_user_costs
    ADD CONSTRAINT monthly_user_costs_pk PRIMARY KEY (billing_month, user_id);


--
-- Name: chatbots chatbots_pk; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.chatbots
    ADD CONSTRAINT chatbots_pk PRIMARY KEY (id);


--
-- Name: chatrooms chatrooms_pk; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.chatrooms
    ADD CONSTRAINT chatrooms_pk PRIMARY KEY (id);


--
-- Name: flyway_schema_history flyway_schema_history_pk; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.flyway_schema_history
    ADD CONSTRAINT flyway_schema_history_pk PRIMARY KEY (installed_rank);


--
-- Name: intimacy_progress intimacy_progress_pkey; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.intimacy_progress
    ADD CONSTRAINT intimacy_progress_pkey PRIMARY KEY (id);


--
-- Name: messages messages_pk; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.messages
    ADD CONSTRAINT messages_pk PRIMARY KEY (id);


--
-- Name: intimacy_progress uq_intimacy_chatroom; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.intimacy_progress
    ADD CONSTRAINT uq_intimacy_chatroom UNIQUE (chatroom_id);


--
-- Name: messages uq_messages_room_seq; Type: CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.messages
    ADD CONSTRAINT uq_messages_room_seq UNIQUE (chatroom_id, sequence_number);


--
-- Name: stores stores_pkey; Type: CONSTRAINT; Schema: store_schema; Owner: doran
--

ALTER TABLE ONLY store_schema.stores
    ADD CONSTRAINT stores_pkey PRIMARY KEY (id);


--
-- Name: app_user app_user_pk; Type: CONSTRAINT; Schema: user_schema; Owner: doran
--

ALTER TABLE ONLY user_schema.app_user
    ADD CONSTRAINT app_user_pk PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: user_schema; Owner: doran
--

ALTER TABLE ONLY user_schema.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: settings settings_pkey; Type: CONSTRAINT; Schema: user_schema; Owner: doran
--

ALTER TABLE ONLY user_schema.settings
    ADD CONSTRAINT settings_pkey PRIMARY KEY (id);


--
-- Name: profiles uk4ixsj6aqve5pxrbw2u0oyk8bb; Type: CONSTRAINT; Schema: user_schema; Owner: doran
--

ALTER TABLE ONLY user_schema.profiles
    ADD CONSTRAINT uk4ixsj6aqve5pxrbw2u0oyk8bb UNIQUE (user_id);


--
-- Name: idx_ai_usage_events_time; Type: INDEX; Schema: billing; Owner: doran
--

CREATE INDEX idx_ai_usage_events_time ON billing.ai_usage_events USING btree (event_time);


--
-- Name: idx_ai_usage_events_user_time; Type: INDEX; Schema: billing; Owner: doran
--

CREATE INDEX idx_ai_usage_events_user_time ON billing.ai_usage_events USING btree (user_id, event_time);


--
-- Name: idx_monthly_user_costs_month; Type: INDEX; Schema: billing; Owner: doran
--

CREATE INDEX idx_monthly_user_costs_month ON billing.monthly_user_costs USING btree (billing_month);


--
-- Name: flyway_schema_history_s_idx; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX flyway_schema_history_s_idx ON chat_schema.flyway_schema_history USING btree (success);


--
-- Name: idx_chatbots_active; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_chatbots_active ON chat_schema.chatbots USING btree (is_active);


--
-- Name: idx_chatbots_created_by; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_chatbots_created_by ON chat_schema.chatbots USING btree (created_by);


--
-- Name: idx_chatbots_type; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_chatbots_type ON chat_schema.chatbots USING btree (bot_type);


--
-- Name: idx_chatrooms_chatbot; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_chatrooms_chatbot ON chat_schema.chatrooms USING btree (chatbot_id);


--
-- Name: idx_chatrooms_last_message; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_chatrooms_last_message ON chat_schema.chatrooms USING btree (last_message_at DESC);


--
-- Name: idx_chatrooms_user; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_chatrooms_user ON chat_schema.chatrooms USING btree (user_id);


--
-- Name: idx_chatrooms_user_chatbot; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE UNIQUE INDEX idx_chatrooms_user_chatbot ON chat_schema.chatrooms USING btree (user_id, chatbot_id) WHERE (NOT is_deleted);


--
-- Name: idx_intimacy_progress_chatroom; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_intimacy_progress_chatroom ON chat_schema.intimacy_progress USING btree (chatroom_id);


--
-- Name: idx_intimacy_progress_user; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_intimacy_progress_user ON chat_schema.intimacy_progress USING btree (user_id);


--
-- Name: idx_messages_chatroom; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_messages_chatroom ON chat_schema.messages USING btree (chatroom_id, sequence_number);


--
-- Name: idx_messages_created_at; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_messages_created_at ON chat_schema.messages USING btree (created_at);


--
-- Name: idx_messages_parent; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_messages_parent ON chat_schema.messages USING btree (parent_message_id);


--
-- Name: idx_messages_sender; Type: INDEX; Schema: chat_schema; Owner: doran
--

CREATE INDEX idx_messages_sender ON chat_schema.messages USING btree (sender_id);


--
-- Name: idx_store_ai_response_gin; Type: INDEX; Schema: store_schema; Owner: doran
--

CREATE INDEX idx_store_ai_response_gin ON store_schema.stores USING gin (ai_response);


--
-- Name: idx_store_chatroom; Type: INDEX; Schema: store_schema; Owner: doran
--

CREATE INDEX idx_store_chatroom ON store_schema.stores USING btree (chatroom_id, created_at DESC) WHERE (is_deleted = false);


--
-- Name: idx_store_user_created; Type: INDEX; Schema: store_schema; Owner: doran
--

CREATE INDEX idx_store_user_created ON store_schema.stores USING btree (user_id, created_at DESC) WHERE (is_deleted = false);


--
-- Name: idx_store_user_message; Type: INDEX; Schema: store_schema; Owner: doran
--

CREATE UNIQUE INDEX idx_store_user_message ON store_schema.stores USING btree (user_id, message_id) WHERE (is_deleted = false);


--
-- Name: app_user_email_idx; Type: INDEX; Schema: user_schema; Owner: doran
--

CREATE UNIQUE INDEX app_user_email_idx ON user_schema.app_user USING btree (email);


--
-- Name: refresh_tokens fk5a9ypl7oycxycfscqnsepj5t8; Type: FK CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.refresh_tokens
    ADD CONSTRAINT fk5a9ypl7oycxycfscqnsepj5t8 FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- Name: email_verifications fk5vri8t8tr81le36apgppy94ch; Type: FK CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.email_verifications
    ADD CONSTRAINT fk5vri8t8tr81le36apgppy94ch FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- Name: login_attempts fkeix6yqtdy2p9t2vj8hs6ji8of; Type: FK CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.login_attempts
    ADD CONSTRAINT fkeix6yqtdy2p9t2vj8hs6ji8of FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- Name: password_reset_tokens fkj9so57i2ys7gbwiljqyrivrnb; Type: FK CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.password_reset_tokens
    ADD CONSTRAINT fkj9so57i2ys7gbwiljqyrivrnb FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- Name: auth_events fkq2wxphtsj555bl7w9yvcr08q8; Type: FK CONSTRAINT; Schema: auth_schema; Owner: doran
--

ALTER TABLE ONLY auth_schema.auth_events
    ADD CONSTRAINT fkq2wxphtsj555bl7w9yvcr08q8 FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- Name: ai_usage_events fk_ai_usage_events_chatroom; Type: FK CONSTRAINT; Schema: billing; Owner: doran
--

ALTER TABLE ONLY billing.ai_usage_events
    ADD CONSTRAINT fk_ai_usage_events_chatroom FOREIGN KEY (chatroom_id) REFERENCES chat_schema.chatrooms(id) ON DELETE SET NULL;


--
-- Name: ai_usage_events fk_ai_usage_events_user; Type: FK CONSTRAINT; Schema: billing; Owner: doran
--

ALTER TABLE ONLY billing.ai_usage_events
    ADD CONSTRAINT fk_ai_usage_events_user FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id) ON DELETE SET NULL;


--
-- Name: chatbots chatbots_created_by_fkey; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.chatbots
    ADD CONSTRAINT chatbots_created_by_fkey FOREIGN KEY (created_by) REFERENCES user_schema.app_user(id) ON DELETE SET NULL;


--
-- Name: chatrooms chatrooms_chatbot_id_fkey; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.chatrooms
    ADD CONSTRAINT chatrooms_chatbot_id_fkey FOREIGN KEY (chatbot_id) REFERENCES chat_schema.chatbots(id) ON DELETE CASCADE;


--
-- Name: chatrooms chatrooms_user_id_fkey; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.chatrooms
    ADD CONSTRAINT chatrooms_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id) ON DELETE CASCADE;


--
-- Name: chatrooms fk_chatrooms_last_message; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.chatrooms
    ADD CONSTRAINT fk_chatrooms_last_message FOREIGN KEY (last_message_id) REFERENCES chat_schema.messages(id) ON DELETE SET NULL;


--
-- Name: messages fk_messages_parent; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.messages
    ADD CONSTRAINT fk_messages_parent FOREIGN KEY (parent_message_id) REFERENCES chat_schema.messages(id) ON DELETE SET NULL;


--
-- Name: intimacy_progress intimacy_progress_chatroom_id_fkey; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.intimacy_progress
    ADD CONSTRAINT intimacy_progress_chatroom_id_fkey FOREIGN KEY (chatroom_id) REFERENCES chat_schema.chatrooms(id) ON DELETE CASCADE;


--
-- Name: intimacy_progress intimacy_progress_user_id_fkey; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.intimacy_progress
    ADD CONSTRAINT intimacy_progress_user_id_fkey FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id) ON DELETE CASCADE;


--
-- Name: messages messages_chatroom_id_fkey; Type: FK CONSTRAINT; Schema: chat_schema; Owner: doran
--

ALTER TABLE ONLY chat_schema.messages
    ADD CONSTRAINT messages_chatroom_id_fkey FOREIGN KEY (chatroom_id) REFERENCES chat_schema.chatrooms(id) ON DELETE CASCADE;


--
-- Name: settings fk5w7p1w60kfsalo61akkmfirv3; Type: FK CONSTRAINT; Schema: user_schema; Owner: doran
--

ALTER TABLE ONLY user_schema.settings
    ADD CONSTRAINT fk5w7p1w60kfsalo61akkmfirv3 FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- Name: profiles fko9irkw5uae1s5s10pmstcvipw; Type: FK CONSTRAINT; Schema: user_schema; Owner: doran
--

ALTER TABLE ONLY user_schema.profiles
    ADD CONSTRAINT fko9irkw5uae1s5s10pmstcvipw FOREIGN KEY (user_id) REFERENCES user_schema.app_user(id);


--
-- PostgreSQL database dump complete
--

\unrestrict k1AwuoK1JB5INgXavvsiHAJKQfNWiM1z5rNrMeziwVwOumkgAZpUxgiJUXe86kg

