spring:
  application:
    name: store-service

  datasource:
    url: jdbc:postgresql://localhost:5432/dorandoran
    username: doran
    password: doran_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: store_schema

  sql:
    init:
      mode: never

server:
  port: 8084

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.dorandoran.store: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Feign Client
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
  chat-service:
    url: http://chat-service:8083
#    url: http://localhost:8083  # 로컬 테스트
  circuitbreaker:
    enabled: true

# OpenAPI/Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method