server:
  port: 8081

spring:
  application:
    name: auth-service
  
  # Auth 서비스 공유 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/dorandoran_local
    username: doran
    password: doran
    driver-class-name: org.postgresql.Driver
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# JWT 설정
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token-expiration: 3600000  # 1시간
      refresh-token-expiration: 604800000  # 7일

# 서비스 간 통신 설정
user:
  service:
    url: http://localhost:8082

# Circuit Breaker 설정
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      user-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  timelimiter:
    instances:
      user-service:
        timeout-duration: 5s

# 로깅 설정
logging:
  level:
    com.dorandoran.auth: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
